### PR TITLE
Feature 56 - delete a tag 

### PR DESCRIPTION
**Pull request by jerushachua**
This feature allows you to delete a tag from the tag list. 

**Implementation** 
- The CSS for implementing a button within the list items for the tags was very ugly, so I implemented the ability to double click to delete tag. 
- Upon a single click, a modal pops up to let the user know that they can double click on a tag to delete it. After this first click, the modal doesn't appear anymore. 
- The changes in the tag list are reflected immediately but the graph is not updated. Issue #105 covers that scope. 

Note: there is a minor bug where you cannot delete tag names with periods in them. This is due to JS being unable to handle function passing of strings with periods in the name. I can open an issue for this for further investigation and am open to suggestions on how to fix it.

### CODE REVIEW

**Comment by SiRumCz** [comment]
I tried with just passing the name string and it seemed to work and it also handles tag string with periods.
As for the design, I think in the future we will need to make a checkout tag function by single-clicking tag.  Also I am not sure if it is just me, I misclicked a lot.. I think a delete button is more intuitive.

**Comment by sterlinglaird** [comment]
I agree with the delete button being more intuitive, especially because that is how the branches are deleted, and that there is an issue (#61) for checking out a tag which will likely be implemented by simply clicking once on the tag name (because that is how branches do it).

**Comment by jerushachua** [comment]
I added a button based on your comments. It should work with all tag name types after my rework of the delete tag function. 

Thanks @SiRumCz and @sterlinglaird for your suggestions!

**Comment by jerushachua** [comment]
Refreshing the graph based on local changed should be fixed in https://github.com/uvicgse/project-virtual-team-1/issues/105! This was just merged to master today.

**Pull request merged**
