### PR TITLE
Feature 186 drag/drop to commit

### PR DESCRIPTION
**Pull request by mehrler12**
This PR adds a few things for #186.

- Drag and drop to commit! You can now commit by dragging the commit box onto the graph

- Keyboard shortcut to commit, for the power users out there ctrl+enter will also activate the commit process.

- Commit button redesign, since the other 2 buttons are now gone the commit button looked weird on it's own

- Commit panel now disables when there are no staged files, this gives a better visual indicator of when you can and can't commit

- Lastly window.alert was causing issues with the drag and drop and was not in line with the rest of the project, this was brought in line with the rest of the project by using displaymodal instead

### CODE REVIEW

**Comment by subahm** [comment]
When I drag and dropped the commit box while the commit was disabled, it showed the message "Cannot commit without a message.....". I think we should update the message to something like "There is nothing to commit" for this scenario.

**Comment by subahm** [comment]
I get the "cannot commit without a commit message...." even after I enter a message before committing, but the functionality works fine.

**Comment by mehrler12** [comment]
@Athenasko 
> Is there any way to fix up the drag and drop such that it doesn't fade out weirdly?

From what I've read about drag and drop it doesn't seem like it, this comes from how chromium handles drag events.

> In addition, should the actual commit button be able to be dragged too since that would be more likely to be attempted than the text box?

Fixed! Thanks


> When you expand the commit box, it covers the command line text rather than pushing it over, and once its at the max size, it is no longer re-sizable and cannot be shrunk no matter what.

Didn't realize you could even do this! Disabled that feature, should no longer be a problem.

> In addition, the commit button without resizing hangs over the left panel side. Doesn't have to be fixed, but just wondering if was designed like that or if its resizing weirdly due to my screen size.

This was done when the footer was converted to use bootstrap. It makes the footer responsive but unfortunately the panel above it doesn't use bootstrap yet.   

> Lastly, the text box when typing throws a lot of keyboard events into the console logs. Is there anyway to suppress this or should those kinds of events always be record? (I'm actually not sure).

Whoops, left a debug log

> Is it possible to also make the commit button show the 'disabled' icon when hovering over it?

Done!

@subahm 

> When I drag and dropped the commit box while the commit was disabled, it showed the message "Cannot commit without a message.....". I think we should update the message to something like "There is nothing to commit" for this scenario.

Disabled the drag when committing is disabled

> I get the "cannot commit without a commit message...." even after I enter a message before committing, but the functionality works fine.

I think this is #171

**Comment by Athenasko** [comment]
@mehrler12 
> From what I've read about drag and drop it doesn't seem like it, this comes from how chromium handles drag events.

How does the commit drag and drop differ from the staged/unstaged changes and stash drag and drops? Those don't seem to have the same problems.

> Didn't realize you could even do this! Disabled that feature, should no longer be a problem.

Great thanks! XD

> This was done when the footer was converted to use bootstrap. It makes the footer responsive but unfortunately the panel above it doesn't use bootstrap yet.

Sounds good. Thanks for clarifying!

**Comment by mehrler12** [comment]
> How does the commit drag and drop differ from the staged/unstaged changes and stash drag and drops? Those don't seem to have the same problems.

Can you send me a screen shot? They do that for me

**Comment by Athenasko** [comment]
> Can you send me a screen shot? They do that for me. Perhaps cause the element is larger the fade out is more pronounced?

That's really odd. I just checked it out and they are doing that now. They shouldn't be though. Previous behaviour it showed the entire section being dragged as it should be. 
unstagedCommitsBefore

I'm not sure what changed, but all the drag and drop stuff should be acting as the image above and not fading.

**Comment by trstndvll** [comment]
Screenshot 2019-06-22 14 25 47

Perhaps this is the cause? May or may not be related, but in header.component.html, starting at line 467, `<div id="delete-upstream-modal" class="modal fade">` seems to have 4 open divs that don't get closed.

**Comment by mehrler12** [comment]
@Athenasko 

> I'm not sure what changed, but all the drag and drop stuff should be acting as the image above and not fading.

So I've been fiddling with this a bunch and this doesn't seem to be something I can affect at all, I can set a new drag image but this also is faded out similarly to the div. I could totally turn off the ghost image if you think that would be better but short of writing our own drag and drop api I don't think we can fix this

@trstndvll 

> Perhaps this is the cause? May or may not be related, but in header.component.html, starting at line 467, `<div id="delete-upstream-modal" class="modal fade">` seems to have 4 open divs that don't get closed.

Totally unrelated but might as well sneak in a fix

**Comment by Athenasko** [comment]
> So I've been fiddling with this a bunch and this doesn't seem to be something I can affect at all, I can set a new drag image but this also is faded out similarly to the div. I could totally turn off the ghost image if you think that would be better but short of writing our own drag and drop api I don't think we can fix this

Huh that's too bad. It might just be better to turn off the ghost image I think. Odd that it changed though. Thanks for investigating it.

**Comment by Athenasko** [comment]
Really sorry @mehrler12. I definitely misunderstood what turning off the ghost image meant. In my head it meant showing the fully colored draggable item just without the fade effect as previous drag and drops have had, and without the ghost effects that is happening now. I don't know exactly why I thought that, but since this is a visual app, if it's not too much trouble I think the ghost effect would be more effective than without it since it becomes confusing.

**Comment by mehrler12** [comment]
> Really sorry @mehrler12. I definitely misunderstood what turning off the ghost image meant. In my head it meant showing the fully colored draggable item just without the fade effect as previous drag and drops have had, and without the ghost effects that is happening now. I don't know exactly why I thought that, but since this is a visual app, if it's not too much trouble I think the ghost effect would be more effective than without it since it becomes confusing.

Yeah, disabling it also breaks a bit of functionality on Mac. I disabled it to check it with James but yeah I think having it is better then not! Thanks for the comments @Athenasko !

**Pull request merged**
