### PR TITLE
Feature 110 rebase ui popup fresh

### PR DESCRIPTION
**Pull request by aeogunmuyiwa**
Issue #111 Added a table that would show each commit and have options for what to do with that commit (squash, pick, reword) as a part of the Rebase UI.

### CODE REVIEW

**Comment by Athenasko** [comment]
image
When opening the interactive popout, there is a weird scrollbar that appears. In addition, if you click out of the interactive popout on the right of scrollbar, it freezes the application.

**Comment by aeogunmuyiwa** [comment]
@Athenasko the scroll bar is present because I made wanted the second modal to display fully. If not it would look like these 
Screen Shot 2019-06-17 at 2 42 51 PM
and you would have to scroll through the second modal

**Comment by Athenasko** [comment]
Couldn't you close the previous modal though before opening the new one? Would that not fix that problem?

**Comment by aeogunmuyiwa** [comment]
@Athenasko Thanks for the catch, It was a design choice, However , I have fixed the issue. You can pull the latest changes and retest it . Thanks

**Comment by nikola-rados** [comment]
Looks really good so far @aeogunmuyiwa! One quick suggestion would be to keep the position of the buttons consistent.  You have `Rebase` and `Abort` and then `Cancel` and `Continue Rebase`... I think it would be better if the order was `Continue Rebase` then `Cancel`. 👍

**Comment by aeogunmuyiwa** [comment]
Thanks @nikola-rados , I have switched the order and pushed the changes

**Comment by aeogunmuyiwa** [comment]
Branch deleted.

**Pull request merged**
