### PR TITLE
Navbar redesign

### PR DESCRIPTION
**Pull request by maxUser**
This PR is a result of issue #130 
The navbar has been redesigned to accommodate the increasing number of icons being added. I am still working on getting the text to centre align underneath each icon. 
I am using a preinstalled package called font-awesome. Unfortunately, version 4.7 is installed and I could not figure out how to update it to the latest version. If someone could do that, the benefits of version 5 or higher are great. Check this link for updating: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
Here is the icon cheatsheet for version 4.7: https://fontawesome.com/v4.7.0/cheatsheet/

### CODE REVIEW

**Comment by hdauvic** [comment]
May I request that the branch icon be changed to `i class="fas fa-code-branch"` [Here](https://fontawesome.com/icons/code-branch?style=solid) so that it is consistent with the branch icon on the graph?

Additionally, the icons for stash, and rebase are a bit confusing without the text. Perhaps something along the lines of a box (`i class="fas fa-box-open"` [Like this?](https://fontawesome.com/icons/box-open?style=solid)) for stash? And rebase looks too much like a refresh button, so I can really see that people will accidentally click it when they want to refresh their repo. Perhaps: `i class="fas fa-network-wired"` [This?](https://fontawesome.com/icons/network-wired?style=solid), `i class="fas fa-project-diagram"` [This?](https://fontawesome.com/icons/project-diagram?style=solid), `i class="fas fa-layer-group"` [This?](https://fontawesome.com/icons/layer-group?style=solid) or `i class="fas fa-object-group"` [This?](https://fontawesome.com/icons/object-group?style=solid)?

My only other criticism is the icons feel small on a large screen. I understand that we want to make it so we can fit more in, however perhaps making them 1.5X the size they are now would be better.

Finally, a small bug: when opening a repo with a long name the icons do not move, and the menu bar no longer expands in size.
**Current branch**
menu

**Master**
pull4

**Comment by maxUser** [comment]
@hdauvic unfortunately, those icons are only available with version 5+. It contains a lot more appropriate icon options. Maybe we can make it an issue to update the package.

**Comment by colinwerner** [comment]
Max, the changes look good.  A few small comments:
1.) Is it possible to put a bit more space between the icons and the text?
2.) the layout is a bit broken for me:
image

**Comment by maxUser** [comment]
Text is now center-aligned underneath the icons

**Comment by hdauvic** [comment]
Looks great! Thanks for changing it. Hopefully we can get it updated to version 5 to have perfect icons someday.

**Pull request merged**
