### PR TITLE
Work around for the tsc errors on npm start

### PR DESCRIPTION
**Pull request by Unimax**
its a workaround.
i did spend around 2 hours trying to fix tsconfig.file so that these error wont come but not able to reduce to 0. the minimum was 235 errors!

so, for now, added this dummy real error.

### CODE REVIEW

**Comment by wliang93** [comment]
Dummy error shows up on the git console in Windows. Looks a lot cleaner at the moment. 
Are the warnings showing up because of SimpleGit? If it is have other people fixed the issue before?

Issue 143

**Comment by Unimax** [comment]
> Dummy error shows up on the git console in Windows. Looks a lot cleaner at the moment.
> Are the warnings showing up because of SimpleGit? If it is have other people fixed the issue before?
> 
> Issue 143

I am pretty sure it's not because of simple-git.

**Comment by Unimax** [comment]
the current solution adds an extra error in the console which is not intended, will reopen after fixing it.

**Comment by dragonprevost** [comment]
Hey @Unimax , do we know the source of the console errors as of now? I am a bit confused about where the errors are coming from since they did not exist last sprint.

**Comment by Unimax** [comment]
> Hey @Unimax , do we know the source of the console errors as of now? I am a bit confused about where the errors are coming from since they did not exist last sprint.

they were there just not shown as a real error is given priority. these errors are output by tsc (type script compiler). they are mainly warning which are shown as error based on our tsconfig.js.

**Pull request merged**
