### PR TITLE
Fix Issue #26: Upgrade Electron and Node versions

### PR DESCRIPTION
**Pull request by jpstoldt**
Upgrade of Electron to version 5 and the latest Node version resolves this file system dialog issue. Installation of Python 2 is required for rebuilding native node modules as part of this upgrade (https://github.com/uvicgse/project-virtual-team-1/wiki/Upgrade-Process)

### CODE REVIEW

**Comment by colinwerner** [comment]
This also fixes #23?

**Comment by jerushachua** [comment]
Is installation of python 2 also a dependency for the first installation with a clean repo?

**Comment by jpstoldt** [comment]
> This also fixes #23?

It does - will change the reference to show that we are fixing #23 and #26

**Comment by jpstoldt** [comment]
> Is installation of python 2 also a dependency for the first installation with a clean repo?

yes, you need Gyp which is part of Python 2 to recompile native node modules for Electron with a clean repo as well  (https://electronjs.org/docs/tutorial/using-native-node-modules)

**Pull request merged**
