### PR TITLE
Issue 24 upgrade angular dependencies

### PR DESCRIPTION
**Pull request by mehrler12**
#24 We were unable to get the project up to a new version of Angular so instead with approval of the PO we updated all the dependencies. Everything is running at the latest version that the version of Angular we are using supports. We also managed to remove a few packages that weren't actually used anywhere in the app making the install a bit smaller. Since this is an infrastructure change it's important to test this fairly extensively. You should be able to install it by just running `npm install`

### CODE REVIEW

**Comment by colinwerner** [comment]
I was able to get it work on a Mac with some changes to the package-lock.json. I am hoping this doesn't break PCs!

We definitely need more eyes and tries on this one!!

@mehrler12 as soon as we get a handful of people testing this, I'll approve it.

**Review by jerushachua — COMMENTED** [review]
Which versions of npm and node did you test with?

**Comment by jpstoldt** [comment]
> Which versions of npm and node did you test with?

I have developed/tested this on Windows with npm 6.9 and Node 12.2

**Review by jerushachua — APPROVED** [review]
Works on windows with npm v 6.9.0 and node 10.16. +1

**Review by ghost — APPROVED** [review]
I have successfully tested the latest Mac compatibility changes with Windows (Node 12.2). I won't comment on code quality of the PR since I am one of the developers.

**Comment by colinwerner** [comment]
Still waiting for 2-3 more people to test this.

**Review by sterlinglaird — APPROVED** [review]
Tested on windows with node v12.3.1 and npm 6.9.0. Didn't find any changes in stability compared to Angular2.

**Review by subahm — APPROVED** [review]
I have tested this on Mac and it works fine.

**Review by roweba — APPROVED** [review]
Tested on Mac with npm 6.9.0 and node v12.3.1, everything looks good!

**Pull request merged**
