### PR TITLE
Feature 178 Update Unpushed Commit Highlight Colours

### PR DESCRIPTION
**Pull request by trstndvll**
Issue #178  This PR changes the colors of the Ahead and Behind badges to match the highlight colors of the unpushed commit nodes in the graph. Ahead is colored red to match the highlight color, and Behind is colored blue to contrast the red (it isn't currently used for anything other than a reference).

Also added a feature where, on hover, the cursor changes to a specified icon. So for hovering on Ahead, the cursor will change to the push icon to tell the user they may want to push. Conversely, hovering on Behind will change the cursor to the pull icon.

### CODE REVIEW

**Comment by trstndvll** [comment]
> May I request making it larger to match the text size of the things around it? Or is that because the numbers won't show on screen if that is done?

@hdauvic totally fair point. The only issue we run into is because we're using the badge element from bootstrap, it has very defined behaviour, one of which is clipping the sides of the div no matter what css properties we change (lol). I've been fighting with it for a while, but I can see if @aeogunmuyiwa or I have some time to try and fiddle with it a bit more. We'll let you know!

**Comment by mehrler12** [comment]
> one of which is clipping the sides of the div no matter what css properties we change (lol)

It's a bit hacky but perhaps adding a negative left margin would work here?

**Comment by aeogunmuyiwa** [comment]
@mehrler12 Yeah you're right, it is a bit hacky so we will just leave it the way it is and merge. both buttons are aligned and do their jobs perfectly.  Thanks for the review :)

**Comment by aeogunmuyiwa** [comment]
Issue closed and merged into master

**Pull request merged**
