### PR TITLE
Fix "Open in Editor" button in Diff Panel

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes issue #201. Pressing "Open in Editor" in Diff panel now opens the text editor for selected file.

### CODE REVIEW

**Review by colinwerner — APPROVED** [review]
So the issue is/was that you moved this component to the header as opposed to the footer?

**Comment by jpstoldt** [comment]
> So the issue is/was that you moved this component to the header as opposed to the footer?

There was a broken object reference since displayFileEditor() is a method of the HeaderComponent class and not FooterComponent

**Review by maxUser — APPROVED** [review]
Good stuff!

**Comment by aeogunmuyiwa** [comment]
looks good and works!

**Review by aeogunmuyiwa — APPROVED** [review]

**Review by hdauvic — APPROVED** [review]
Works as intended, but it should be noted that this does _not_ fix issue #159 - just in case.

**Pull request merged**
